/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionContent: typeof import('radix-vue')['AccordionContent']
    AccordionHeader: typeof import('radix-vue')['AccordionHeader']
    AccordionItem: typeof import('radix-vue')['AccordionItem']
    AccordionRoot: typeof import('radix-vue')['AccordionRoot']
    AccordionTrigger: typeof import('radix-vue')['AccordionTrigger']
    DialogClose: typeof import('radix-vue')['DialogClose']
    DialogContent: typeof import('radix-vue')['DialogContent']
    DialogOverlay: typeof import('radix-vue')['DialogOverlay']
    DialogPortal: typeof import('radix-vue')['DialogPortal']
    DialogRoot: typeof import('radix-vue')['DialogRoot']
    DialogTrigger: typeof import('radix-vue')['DialogTrigger']
  }
}
